### ISSUE TITLE
What is the size of package-size?

### ISSUE THREAD

**Issue by Hum4n01d** [egoist/package-size#10]
This may sound silly, but I’m on cell data and I’d like to know the size of the `package-size` repository before I use it! :joy: (If I missed it somewhere in the repository, sorry about that)

**Comment by egoist** [comment]
The size of package-size actually doesn't really matter since it's node lib, the main use case is to get size of browser libs.

**Comment by Hum4n01d** [comment]
:(

**Comment by egoist** [comment]
you can simply do `du -sh node_modules` for node modules.

**Comment by arve0** [comment]
```sh
$ du -h -d 1 node_modules/package-size
 12K	node_modules/package-size/lib
 42M	node_modules/package-size/node_modules
 42M	node_modules/package-size
```

**Comment by arve0** [comment]
My previous comment does not reflect download size, as packages are gzipped in a tarball. I've created [a tool to get download size of npm packages](https://www.npmjs.com/package/download-size):

```
$ download-size package-size
7.71 MiB
```

**Comment by styfle** [comment]
@Hum4n01d @arve0 Package Phobia should solve your problem https://github.com/styfle/packagephobia
