### ISSUE TITLE
Incorrect sizes?

### ISSUE THREAD

**Issue by Siilwyn** [egoist/package-size#13]
Not sure what's happening here:
Running: `npx package-size wreck got`, outputs:
```
  package       size     minified  gzipped
  wreck@14.0.2  1.16 MB  429 kB    137 kB
  got@8.3.0     410 kB   139 kB    43.8 kB
```

Looking at the output `wreck` looks huge. However if I locally install both tools and inspect the total size of `node_modules` I get this:
```
  package       size
  wreck@14.0.2  111 kB
  got@8.3.0     581 kB
```

I understand that `package-size` doesn't look at the modules size but instead the bundle size still these results don't make sense right? How can the bundled size be 10 times bigger than the source?

**Comment by egoist** [comment]
> bundle size still these results don't make sense right

The bundle size for a Node.js library doesn't make sense, sure, this tool is mainly for browser libraries. Related #10

**Comment by Siilwyn** [comment]
Aha, thank you for your reply. I still find it odd it's ten times bigger but okay.

**Comment by Siilwyn** [comment]
For posterity, I found this awesome service to measure the size of Node.js modules: [Package Phobia](https://packagephobia.now.sh/).

**Comment by styfle** [comment]
@Siilwyn Yep, that's what Package Phobia was designed for 😄 

I also made note of similar tools in the readme if this type of thing interests you: https://github.com/styfle/packagephobia#how-is-this-different
