### ISSUE TITLE
Add support for ES6 packages

### ISSUE THREAD

**Issue by bfred-it** [egoist/package-size#4]
UglifyJS isn't ES6+ compatible, for example:

```sh
$ package-size zooming

ERROR in zooming.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [zooming.js:86,30]
```

A possible solution would be using [babili](https://github.com/babel/babili)

**Comment by egoist** [comment]
sounds reasonable, I might add this later (PR welcome), currently you can use `--es6` option to get the size of compiled file.

**Comment by bfred-it** [comment]
Ah, that's not bad either. I had RTFM and then promptly forgot about it :D

**Comment by bfred-it** [comment]
Works now! Thanks :)

```
$ package-size lodash-es

  package            size     minified  gzipped
  lodash-es@4.17.10  1.76 MB  100 kB    31.6 kB
```
