### ISSUE TITLE
Support for missing dependencies

### ISSUE THREAD

**Issue by drcmda** [egoist/package-size#6]
This module is awesome, but it kept crashing on some libs i've tried, usually `Module not found: Error: Can't resolve '...'`

```
❯ package-size preact-compat       

  package        size  minified  minified+gzipped
  preact-compat  ...   ...       ...


 ERROR  Compiled with errors!

Error: 
ERROR in /private/var/folders/n6/2ys_sbln60d7hlwngzqzs_p80000gn/T/package-size-lwt529m5lmpylqjbutyb9/~/preact-compat/dist/preact-compat.es.js
Module not found: Error: Can't resolve 'preact' in '/private/var/folders/n6/2ys_sbln60d7hlwngzqzs_p80000gn/T/package-size-lwt529m5lmpylqjbutyb9/node_modules/preact-compat/dist'
 @ /private/var/folders/n6/2ys_sbln60d7hlwngzqzs_p80000gn/T/package-size-lwt529m5lmpylqjbutyb9/~/preact-compat/dist/preact-compat.es.js 2:0-69
 @ multi preact-compat
    at /usr/local/lib/node_modules/package-size/lib/index.js:114:11
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/package-size/node_modules/co/index.js:65:19)

**Comment by egoist** [comment]
Hmm, it sounds good to check if the package has `peerDependencies` first, but for now you can edither `package-size preact-compat,preact` to get full size or `package-size preact-compat --externals preact` to get size of preact-compat only

**Comment by egoist** [comment]
<img width="761" alt="2017-04-05 6 25 41" src="https://cloud.githubusercontent.com/assets/8784712/24701506/4a86e6c2-1a2d-11e7-8b2c-f9afe22c38ea.png">

It works fine now, `peerDependencies` are automatically excluded.
