### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by umarashfaq** [egoist/package-size#9]
Doesn't work by adding `--es6` either.
<img width="765" alt="screen shot 2017-05-28 at 3 57 55 pm" src="https://cloud.githubusercontent.com/assets/1681120/26528183/7745009e-43be-11e7-90d0-4dd08c1eefb6.png">

**Comment by egoist** [comment]
What's your node.js version? it only works on node 4+

**Comment by umarashfaq** [comment]
4.3.2

**Comment by egoist** [comment]
Hmm, seems `default parameter` is only supported in node 6+
